# select = [
#     "E", "F", "UP", "W", 
#     "C90", "YTT", "ASYNC", "S", 
#     "B", "COM", "C4", "DTZ",
#     "SLF", 
# ]

select = ["SIM"]
#select = ["FBT", "I", "BLE", "E722"]

# skip line length and use of bare "except"
#ignore = ["E501", "E722", "F401", "F541", "S311"]

# Group violations by containing file.
format = "grouped"

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    "src/nestup.py",
    "src/dmx/",
    "src/nested-tuplets/",
    ".git",
    ".mypy_cache",
    ".ruff_cache",
]
per-file-ignores = {}

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py311"

[pylint]
max-branches = 12
max-returns = 6

[mccabe]
max-complexity = 12
